### ISSUE TITLE
Ошибка в нейминге

### ISSUE THREAD

**Issue by igosheva** [elarkov/coworking#15]
https://github.com/elarkov/coworking/blob/63e97ab618788d4252debe18636488f20e21d022/index.html#L172

**Comment by igosheva** [comment]
Имя элемента должно строиться не от предыдущего элемента, а от основного блока по схеме Б__Э, т.е например box__text

**Comment by igosheva** [comment]
Тоже самое в дочерних и соседних элементах футера

**Comment by elarkov** [comment]
исправил.
