### ISSUE TITLE
Шрифт не по макету

### ISSUE THREAD

**Issue by igosheva** [elarkov/coworking#18]
https://github.com/elarkov/coworking/blob/37f5f9ef71c2f0faa33bef7fc685d691c4250773/css/section/sidebar.css#L48

**Comment by igosheva** [comment]
Если применить из своего проекта вот этот шрифт font-family: "gothapro", sans-serif; все норм становится

**Comment by elarkov** [comment]
Исправил, поставил везде "gothapro", sans-serif;
