### ISSUE TITLE
Вот этого точно быть не должно)

### ISSUE THREAD

**Issue by igosheva** [elarkov/coworking#23]
https://github.com/elarkov/coworking/blob/37f5f9ef71c2f0faa33bef7fc685d691c4250773/css/section/sidebar.css#L51

**Comment by igosheva** [comment]
Лучше везде для line-height используй относительные единицы, например в данном случае 1. Схема расчета line-height равно font-size*значение line-height

**Comment by elarkov** [comment]
Исправил
