### ISSUE TITLE
Нужно отпозиционировать элементы от li

### ISSUE THREAD

**Issue by igosheva** [elarkov/coworking#29]
https://github.com/elarkov/coworking/blob/37f5f9ef71c2f0faa33bef7fc685d691c4250773/css/main.min.css#L2288

**Comment by igosheva** [comment]
Иначе сейчас если отдаляешь получается это http://joxi.ru/1A5aD8gsKJQDzA
Для позиционирования от li нужно добавить к li свойство     position: relative;

**Comment by elarkov** [comment]
исправил)
