### ISSUE TITLE
Элемент навигации - это прежде всего ссылка

### ISSUE THREAD

**Issue by igosheva** [elarkov/coworking#8]
https://github.com/elarkov/coworking/blob/63e97ab618788d4252debe18636488f20e21d022/index.html#L43

**Comment by igosheva** [comment]
Нужно обернуть в ссылку картинку и текст., так как кликабельной должна быть вся область элмента навигации, включая картинку. Соответственное - элемент menu__link будет просто span.

**Comment by elarkov** [comment]
исправил.
